### ISSUE TITLE
Cannot render page with path "\index", did you mean "/\index"?

### ISSUE THREAD

**Issue by mmdzov** [kyle-mccarthy/nest-next#83] opened 2022-01-14 16:25 UTC
**Describe the bug**
I tried all the methods and when I tried to run ```yarn start: dev```, I got the following error but I could not find any solution.

```Cannot render page with path "\index", did you mean "/\index"?. See more info here: https://nextjs.org/docs/messages/render-no-starting-slash ```

I used any kind of educational article, I went all the way correctly but this bug was in front of my eyes.

**Expected behavior**
I expected the index path to be rendered successfully but 404 was executed **and more importantly the above error is displayed to me on the console**

Repository URL:  https://github.com/mmdzov/nest-next-monorepo

**Version**
- next.js: **12.0.8**
- nest: **8.1.1**
- nest-next: **9.5.0**

**Comment by kyle-mccarthy** [comment] 2022-01-14 22:19
HI, thanks for reporting this. I am pretty sure it is a duplicate of #82, are you on windows?

**Comment by mmdzov** [comment] 2022-01-14 23:06
> HI, thanks for reporting this. I am pretty sure it is a duplicate of #82, are you on windows?

you're welcome.
Yes, I'm on Windows.

**Comment by kyle-mccarthy** [comment] 2022-01-14 23:26
I don't have a windows machine to test this on, but I am pretty sure that this change would fix the issue. Is it possible for you to run this and let me know if the output is what you would expect?

```
const path = require('path');
const output = path.posix.normalize("/path/to/file");
console.log(output);
```

I want to verify that it is `/path/to/file` rather than `\path\to\file`.

**Comment by mmdzov** [comment] 2022-01-15 01:05
I executed it and the output was ```/path/to/file```

**Comment by kyle-mccarthy** [comment] 2022-01-18 18:18
Hi @mmdzov [I published a new version](https://www.npmjs.com/package/nest-next/v/9.6.0) with a fix for this!

**Closed by kyle-mccarthy** 2022-01-18 18:18 UTC
